---
title: "Numbers and figures requested for Prelim report"
date: "`r Sys.Date()`"

## Options for outputting HTML

# output:
#   rmarkdown::html_document:
#     theme: cerulean
#     toc: true
#     toc_depth: 2
#     toc_float: true
# 


# # Options for outputting PDF
# output:
#   bookdown::pdf_document2:
#     fig_caption: yes
#     toc: true
#     number_sections: true
#     latex_engine: xelatex
#     includes:
#       in_header: preamble.tex
# mainfont: Avenir
# fontsize: 10pt
# geometry: left=2cm,right=2cm,top=2.5cm,bottom=2cm


# Options for outputting Word
output: word_document
fontsize: 10pt


## Other options
# editor_options: 
#   chunk_output_type: console
# params: 
#   mode: "word"
---
\newpage

```{r readData, echo = FALSE, warning = F, message = F}

addTaskCallback(function(...) {set.seed(123);TRUE})

library(here)
source(here("scripts/load.R"))
```

```{r utilityFunctions}
source(here("scripts/utils.R"))
```


# Table 1 Sociodemographic characteristics of the final sample

```{r}
source(here("scripts/sample_characteristics_2.R"))
sample_characteristics_2_table
```


# Figure 2: Crude seroprevalence

```{r fig.width = 7.17, fig.height = 8.22}
source(here("scripts/seropos_euler.R"))
source(here("scripts/pos_age_sex_pyramid.R"))

top_plots <- 
  cowplot::plot_grid(plot_grid(seropos_euler_plot, scale = 0.9), 
                   pos_age_sex_pyramid_plot, 
                   nrow = 1, 
                   rel_widths = c(3,7.6), labels = c("A", "B"))

source(here("scripts/map2.R"))

cowplot::plot_grid(top_plots, 
                   plot_grid(map2_plot, labels = "C"), 
                   ncol = 1, 
                   rel_heights = c(3,6)
                   )

```


# Table 2 Population-weighted and test-adjusted seroprevalence estimates 

```{r}
source(here("scripts/sero_estim.R"))

igg_pos_table_print
```


# Fig. 3 Risk factor analysis for SARS-CoV-2 IgG seropositivity

```{r fig.width = 7.4, fig.height = 7.7}
source(here("scripts/infection_regn.R"))

infection_regn_plot
```

# Fig. 4 Symptomatiticity among IgG seropositive and seronegative respondents

```{r fig.width = 7.4, fig.height = 7.8}
neg_color <- alpha("dodgerblue2", 0.7) 
pos_color <- alpha("firebrick3", 0.7)
text_color <- "firebrick4"

symptoms_among_igg_positive <- 
  yao %>%
  filter(cat_igg_result == "Positive") %>%
  filter(mcat_symp != "No symptoms") %>% 
  plot_upset2(mcat_symp,
             sep = "--",
             intersect_cutoff =  2,
             subtitle = "",
             fill = pos_color, 
             denom =  yao %>% filter(cat_igg_result == "Positive"),
             set_size_lab = "Prevalence \n(% and No. with this symptom)",
             intersect_size_lab = "Co-prevalence, \n(% and no. with this combination of symptoms)"
             ) %>% 
  plot_grid() +
  labs(caption = "of 302 IgG seropositive individuals") + 
  theme(plot.caption = element_text(size = 6.5, color = "gray10", hjust = 1, family = "Avenir Next"))



source(here("scripts/seropos_symptoms_euler.R"))
source(here("scripts/symptoms_per_sero_cat_plot.R"))


plot_grid(
  plot_grid(plot_grid(seropos_symptoms_euler_plot, scale = 0.8), 
            plot_grid(symptoms_among_igg_positive, scale = 0.98), ncol = 1, labels = "AUTO"),
  plot_grid(symptoms_per_sero_cat_plot, scale = 0.98), 
  ncol = 2, rel_widths = c(4.5,5.5),
  labels = c("","C"))

```


# Supplementary Figure 1

```{r fig.width=5.5, fig.height=6.88}
source(here("scripts/trend_over_time.R"))

trend_over_time_plot


```














