---
title: "Univariate plots of Yaounde COVID study data"


### Options for outputting HTML
# 
# output:
#   rmarkdown::html_document:
#     theme: cerulean
#     toc: true
#     toc_depth: 2
#     toc_float: true
# 


# Options for outputting PDF
output:
  bookdown::pdf_document2:
    toc: true
    number_sections: false
    latex_engine: xelatex
    includes:
      in_header: preamble.tex
mainfont: Avenir
fontsize: 10pt
geometry: left=2cm,right=2cm,top=2.5cm,bottom=2cm
# 
# ## Options for outputting Word
# output: word_document
# fontsize: 10pt
# geometry: left=2cm,right=2cm,top=2.5cm,bottom=2cm

## Other options
editor_options: 
  chunk_output_type: console
params: 
  mode: "pdf"
---

\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F, dpi = 300,
                      fig.width = 6, 
                      fig.height = 1.75,
                      fig.align = "center" )

# force figures not to float
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")


# params$mode <- "pdf"

library(pacman)

p_load(
       "readxl",
       "here",
       "janitor",
       "stringi",
       "usethis",
       "renv",
       "plotly",
       "vegan",
       "reshape2",
       "viridis",
       "GGally",
       "heatmaply",
       "superheat",
       "styler",
       "paletteer",
       "scales",
       "ggtext",
       "inspectdf",
       "purrr",
       "scales",
       "lubridate",
       "highcharter",
       "leaflet",
       "ExPanDaR",
       "ggupset",
       "gridExtra",
       "UpSetR", ##devtools::install_github("NightingaleHealth/ggforestplot")
       "magrittr",
       "devtools",
       "ggforestplot",
       "gt", 
       "kableExtra",
       "huxtable",
       "tidyverse", 
       "patchwork"
       )


# usethis::use_github(protocol = "https", auth_token = Sys.getenv("GITHUB_PAT"))

# 
# # palette
# my_palette <- c("#56bfa3", "#f79f57" ,"#7570B3","#56B4E9",  #greenblue #lightorange #purplepastel  #lightblue
#                 "#3758a6" , "#CC79A7" , "#91142c", "#eb4034", #darkblue #pinkpurple #wine #orange
#                 "#a3b0c4", "#870476", "#479444", "#3cd6d6" ) # grey, # royalpurple #darkgreen # cyan
# 
my_palette <- paletteer_d("awtools::bpalette") %>% as.character() %>% str_sub(end = 7)

scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = my_palette)
}

scale_fill_discrete <- function(...) {
  scale_fill_manual(..., values = my_palette)
}


# theme
my_theme <- theme_classic() +
  theme(text = element_text( size = 12.5),
        rect = element_blank(), # transparent background
        plot.title = (element_text(face = "bold", hjust = 0.5, size = 13)),
        plot.subtitle = (element_text( hjust = 0.5, size = 8, color = alpha("black", 0.7))),
        plot.caption = element_text(size = 6.5, color = "gray50", hjust = 1),
        legend.position = "bottom",
        legend.text = element_text(size = 8),
        legend.key.size = unit(1,"line"),
        axis.title = element_text(size = 10),
        axis.text = element_text(size = 9 ),
        axis.line = element_line(color = "gray40", size = 0.5),
        axis.line.y = element_blank(),
        panel.grid.major = element_line(color = alpha("gray50", 0.1), size = 0.25), 
        strip.background = element_blank(),
        strip.text = element_text(face = "bold", color = 'white'),
        panel.spacing.x = unit(3, "mm"), 
        title = element_text(face = "bold"), 
        panel.border = element_blank(),
        plot.background = element_rect(fill = "#f5f5f5"), 
        panel.background = element_rect(fill = "white")
        #strip.background = element_blank()
        )

theme_set(my_theme)

options(scipen=999) # turn off scientific notation

options(tibble.print_max = 30, tibble.print_min = 30)
# 
# category_names <- 
#   read_excel(here("data/EPICO19_-_all_versions_26 11 approved.xlsx"), sheet = 3) %>% 
#   select(raw_name) %>% 
#   separate(raw_name, into = c("var", "category"), sep = "/") %>% 
#   select(category) 
# 
# write_excel_csv(category_names, file = here("data/category_names.csv"), na = "")
#   
# 

```

```{r utilityFunctions}
source(here("scripts/utils.R"))

```

```{r readData}
yao_raw <- 
  read_excel(here("data/EPICO19_-_all_versions_26 11 approved.xlsx"), sheet = 1) %>% 
  type_convert()


## read in clean names and replace
data_dict <- read_excel(here("data/EPICO19_-_all_versions_26 11 approved.xlsx"), sheet = 3)

raw_name <- data_dict$raw_name
clean_name <- data_dict$clean_name
axis_name <- data_dict$axis_name 

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~  We sort the replacements in descending order of length ----
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# this should reduce problems 
raw_category <- 
  data_dict %>% 
  select(raw_category) %>% 
  mutate(raw_category = ifelse(is.na(raw_category), "PLACEHOLDER_TEXT_PLACEHOLDER_TEXT",  raw_category)) 

clean_category <- 
  data_dict %>% 
  select(clean_category) %>% 
  mutate(clean_category = ifelse(is.na(clean_category), "PLACEHOLDER_TEXT_PLACEHOLDER_TEXT",  clean_category)) 

# place together and arrange so order is preserved
category_dictionary_tib <- 
  tibble(raw_category, clean_category) %>% 
  mutate(length = str_length(raw_category)) %>% 
  arrange(-length)

raw_category <-  category_dictionary_tib$raw_category 
clean_category <-  category_dictionary_tib$clean_category 

category_dictionary <- setNames(object = clean_category, nm = raw_category)


yao <-
  yao_raw %>%
  ## add counter column. 1 for all real records. Useful for counting later (where we use 0 for fake records)
  mutate(counter = 1) %>% 
  ## rename to new names
  rename_with(.cols = any_of(raw_name), .fn = ~ clean_name[which(raw_name == .x)]) %>%
  # select(where( ~ !(all(is.na(.x)) | all(.x=="")) )) %>%
  ## remove rows with double slash in id
  mutate(id_quest = str_replace(id_quest, "//", "/")) %>%
  ## remove accents
  mutate(id_quest = stri_trans_general(id_quest, "Latin-ASCII")) %>%
  ## separate questionnaire id then recombine to form unique household id and individual id
  separate(id_quest, into = c("loc_hhld", "id_hhld_letter", "id_hhld_num", "id_ind_num"), sep = "/", remove = F) %>%
  mutate(loc_hhld = str_replace_all(loc_hhld, "NKOMNKANA", "NKOMKANA")) %>%
  mutate(id_hhld = paste(loc_hhld, id_hhld_num, sep = "_")) %>%
  mutate(id_ind = paste(loc_hhld, id_hhld_num, id_ind_num, sep = "_")) %>%
  relocate(id_hhld, id_ind, .before = everything()) %>%
  ## arrange by these ids
  arrange(loc_hhld, id_hhld_num, id_ind_num) %>%
  filter(id_quest != "MOKOLO/KAR/013/0003") %>%
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~  Clean multi-answer columns ----
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    mutate(across( .cols = matches("mcat"), 
                 .fns = ~ str_replace_all(.x, " ", "--") 
                 )) %>% 
    mutate(across( .cols = matches("mcat"), 
                 .fns = ~ str_replace_all(.x, category_dictionary)
                 )) %>% 
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~  Clean single-answer columns ----
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # education level
  mutate(cat_educ = case_when(cat_educ == "ecole_secondaire" ~ "Secondary", 
                              cat_educ == "ecole_primaire" ~ "Primary", 
                              cat_educ == "universit" ~ "University", 
                              cat_educ == "aucune_instruction_officielle" ~ "No formal instruction", 
                              cat_educ == "doctorat" ~ "Doctorate", 
                              cat_educ == "autre" ~ "Other", 
                              TRUE ~ cat_educ)) %>% 
  mutate(cat_symp_severity = case_when(cat_symp_severity == "sympt_mes_mod_r_s" ~ "Moderate", 
                                       cat_symp_severity == "sympt_mes_s_v_res" ~ "Severe", 
                                       TRUE ~ cat_symp_severity)) %>% 
  mutate(has_mem_lost_job = case_when(has_mem_lost_job == "perte_totale_du_travail_revenus" ~ "Complete loss of work income", 
                                      has_mem_lost_job == "pas_de_perte_de_travail_revenus" ~ "No loss of work income", 
                                      has_mem_lost_job == "diminution_du_temps_de_travail_revenus" ~ "Reduction in work income", 
                                      TRUE ~ has_mem_lost_job)) %>%
  mutate(has_partic_COVID_study = recode(has_partic_COVID_study, 
                                         "ne_sais_pas" = "Don't Know")) %>% 
  mutate(has_tested = recode(has_tested, 
                             "ne_r_ponds_pas__inappropri__ne_sait_pas_" = "No response"
                             )) %>% 
  mutate(is_smoker = recode(is_smoker, 
                            "No_fumeur__je_n_ai_jamais_fum" = "Non-smoker (I've never smoked)", 
                            "fumeur__je_fume_actuellement" = "Smoker (I currently smoke)", 
                            "ex_fumeur__j_ai_fum__mais_ne_fume_plus" = "Ex-smoker (I used to smoke but stopped)"
                            ), 
         is_smoker = if_else(str_detect(is_smoker, "jamais"), 
                             "Non-smoker (I've never smoked)", 
                             is_smoker) ) %>% 
  mutate(has_contact_COVID = recode(has_contact_COVID, 
                                    "je_ne_sais_pas" = "I don't know"
                                    )) %>% 
  mutate(has_contact_traveller = recode(has_contact_traveller, 
                                    "je_ne_sais_pas" = "I don't know"
                                    )) %>% 
  mutate(rate_virus_serious = recode(rate_virus_serious, 
                                     "plus_haut_que_les_autres_personnes" = "More than other people's", 
                                     "moins_que_les_autres_personnes" = "Less than other people's", 
                                     "comme_les_autres_personnes" = "The same as other people's"
                                     )) %>% 
   #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~  Clean across multiple columns ----
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ## replace ne repond pas variants with No response
  mutate(across(.cols = function(.x) is.character(.x) | is.factor(.x) , .fns = function(.x) str_replace_all(.x, "ne_r_pond_pas__inappropri__ne_sait_pas__", "No response"))) %>%
  mutate(across(.cols = function(.x) is.character(.x) | is.factor(.x) , .fns = function(.x) str_replace_all(.x, "ne_r_pond_pas__inappropri__ne_sait_pas_", "No response"))) %>%
  mutate(across(.cols = function(.x) is.character(.x) | is.factor(.x) , .fns = function(.x) str_replace_all(.x, "ne_peut_pas_r_pondre__inappropri__ne_sai", "No response"))) %>%
  mutate(across(.cols = function(.x) is.character(.x) | is.factor(.x) , .fns = function(.x) str_replace_all(.x, "ne_r_pond_pas__inappropri__ne_", "No response"))) %>%
  mutate(across(.cols = function(.x) is.character(.x) | is.factor(.x) , .fns = function(.x) str_replace_all(.x, "non", "No"))) %>%
  mutate(across(.cols = function(.x) is.character(.x) | is.factor(.x) , .fns = function(.x) str_replace_all(.x, "oui", "Yes")))

## Subset and count households with at least one head
yao_hhld_heads <- 
  yao %>%
  # keep only household heads
  filter(is_head == "Yes") %>%
  # pick the first household head if multiple
  group_by(id_hhld) %>%
  arrange(id_ind) %>%
  slice_head(n = 1) %>%
  # ungroup
  ungroup()

yao_hhld_first_adults <- 
  yao %>% 
  # add counter for excluding non-headed households
  mutate(is_head_counter = if_else(is_head == "Yes", 1, 0)) %>%
  group_by(id_hhld) %>%
  # keep households without a head
  filter(sum(is_head_counter) == 0) %>%
  # keep adults
  filter(val_age >= 18) %>%
  # take the first adult 
  arrange(id_ind_num) %>% 
  slice_head(n = 1) %>%
  # ungroup
  ungroup()


yao_hhld  <- 
  yao_hhld_heads %>% 
  bind_rows(yao_hhld_first_adults)

# 
# #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# #~  Household count ----
# #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 
# ## Subset and count households with at least one head
# yao %>% 
#   group_by(id_hhld) %>% 
#   filter(is_head == "Yes") %>% 
#   arrange(id_hhld, id_ind) %>% 
#   # pick the first household head if multiple
#   slice_head(n = 1) %>% 
#   ungroup() %>% 
#   dim()
# ## there are 171 of them
# 
# 
# ## subset and count household with no head
# yao %>% 
#   mutate(is_head_counter = if_else(is_head == "Yes", 1, 0)) %>% 
#   group_by(id_hhld) %>% 
#   # keep households without a head
#   filter(sum(is_head_counter) == 0) %>% 
#   slice_head(n = 1) %>% 
#   ungroup() %>% 
#   dim()
# ## there are 49 of them
# 
# 
# 
# 
# ## do all households without heads have at least one adult?
# yao %>% 
#   mutate(is_head_counter = if_else(is_head == "Yes", 1, 0)) %>% 
#   group_by(id_hhld) %>% 
#   # keep households without a head
#   filter(sum(is_head_counter) == 0) %>% 
#   filter(val_age >= 18) %>% 
#   slice_head(n = 1) %>% 
#   ungroup() %>% 
#   dim()
# ## no. Only 45 no-head households have an adult in them
# 
# 
# ## lets look at the households which do not have an adult within them
# yao %>% 
#   mutate(is_head_counter = if_else(is_head == "Yes", 1, 0)) %>% 
#   mutate(is_adult_counter = if_else(val_age >= 18 , 1, 0)) %>% 
#   group_by(id_hhld) %>% 
#   ## keep households without a head
#   filter(sum(is_head_counter) == 0) %>% 
#   ## keep households without an adult
#   filter(sum(is_adult_counter) == 0) %>% 
#   ungroup() %>% 
#   select(id_hhld, id_ind, val_age)
# ## they look to mostly consist of recoding errors

# 
# yao %>% 
#   select(where( ~ length(unique(.x)) < 10)) %>% 
#   select(where( ~ length(unique(.x)) > 1)) %>% 
#   select( !matches("mcat")  ) %>% 
#   select( !matches("unknown")  ) %>% 
#   select( !starts_with("is_")  ) %>% 
#   select( !starts_with("has")  ) %>% 
#   select(!matches("0") & !matches("1") & !matches("2") & !matches("3") & !matches("4")&  !matches("5")  ) %>% 
#   select(!matches("other")) %>% 
#   inspect_cat() %>%
#   show_plot(col_palette = 1) 
# 
# yao %>% 
#   select(where( ~ length(unique(.x)) > 1)) %>% 
#   # select( !matches("mcat")  ) %>% 
#   select( !matches("unknown")  ) %>% 
#   select( !starts_with("has")  ) %>% 
#   select( !starts_with("is_")  ) %>% 
#   select(!matches("0") & !matches("1") & !matches("2") & !matches("3") & !matches("4")&  !matches("5")  ) %>% 
#   select(!matches("other")) %>% 
#   inspect_num() %>%
#   show_plot(col_palette = 1)  + 
#   theme(strip.background = element_rect(fill = "black"))

# 
# 
# mutate(across(.cols = where(~ length(unique(.x)) < 10),
#                 .fns =  ~ as.factor(.x))) %>%
#   # distribution of factor variables
#   inspect_num() %>%
#   show_plot(col_palette = 1) + 
#   labs(subtitle = "Numeric vars. with 9 or fewer unique values were converted to factors")

```

\newpage

# 10 Difficulty of access to care for COVID-like symptoms

## 10.1 Do you think that your risk of getting infected with the new virus is...?

```{r}

```





