---
title: "main"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Packages

```{r}
library(pacman)

p_load("tidyverse",
       "readxl",
       "here",
       "janitor",
       "stringi",
       "usethis",
       "renv",
       "plotly",
       "vegan",
       "reshape2",
       "viridis",
       "heatmaply",
       "superheat",
       "styler",
       "paletteer",
       "scales",
       "purrr",
       "scales"
       )

# usethis::use_github(protocol = "https", auth_token = Sys.getenv("GITHUB_PAT"))


```

## Read data, clean


```{r}
df_raw <- read_excel(here("data/EPICO19_-_all_versions_26 11 approved.xlsx"), sheet = 2)

## read in clean names and replace
data_dict <- read_excel(here("data/EPICO19_-_all_versions_26 11 approved.xlsx"), sheet = 3, range = "A1:D366")

oldnames <- data_dict$raw_name
newnames <- data_dict$clean_name

# newnames <- paste0(data_dict$clean_name, data_dict$`redundant?`) %>% str_replace("NA", "")


df <- 
  df_raw %>% 
  ## rename to new names
  rename_with( .cols = any_of(oldnames), .fn = ~ newnames[which(oldnames == .x)]) %>% 
  select(!contains("unknown") # & 
           # !contains("redund")  
         ) %>% 
  # select(where( ~ !(all(is.na(.x)) | all(.x=="")) )) %>% 
  ## remove rows with double slash in id
  mutate(id_quest = str_replace(id_quest, "//", "/")) %>% 
  ## remove accents
  mutate(id_quest = stri_trans_general(id_quest, "Latin-ASCII"))  %>% 
  ## separate questionnaire id then recombine to form unique household id and individual id
  separate(id_quest, into = c("loc_hhld", "id_hhld_letter", "id_hhld_num" , "id_ind_num"), sep = "/", remove = F)  %>% 
  mutate(loc_hhld = str_replace_all(loc_hhld, "NKOMNKANA", "NKOMKANA")) %>% 
  mutate(id_hhld = paste(loc_hhld, id_hhld_num, sep = "_")) %>% 
  mutate(id_ind = paste(loc_hhld, id_hhld_num, id_ind_num,  sep = "_")) %>% 
  relocate(id_hhld, id_ind,  .before = everything()) %>% 
  arrange(loc_hhld, id_hhld_num, id_ind_num ) %>% 
  filter(id_quest != "MOKOLO/KAR/013/0003")

df_raw$group_fl2ht56_deces_1_note
```


## Analysis of symptoms

```{r}
symp_clean <- df %>%
  # sample_n(100) %>%
  # select columns concerning symptoms
  select(id_ind, matches("has_symp_")) %>%
  # drop "none" and "other" levels
  select(!matches("none|other"))  %>%
  # melt
  pivot_longer(cols = 2:ncol(.), names_to = "symp") %>%
  # to numeric
  mutate(value = as.numeric(value)) %>%
  # drop individuals with no symptoms
  group_by(id_ind) %>%
  filter(sum(value) > 0) %>% ungroup() %>%
  # drop symptoms with no sufferers
  group_by(symp) %>%
  filter(sum(value) > 0) %>% ungroup() %>% 
  # neaten names
  mutate(symp = str_replace_all(symp, "has_symp_", ""), 
         symp = str_replace_all(symp, "_", " "))


## cluster individuals
individual_cluster <- 
  symp_clean %>% 
  pivot_wider(names_from = symp, values_from = value) %>% 
  column_to_rownames(var="id_ind") %>%
  # compute distances
  vegdist() %>% 
  # cluster
  hclust() 

## cluster symptoms
symp_cluster <- 
  symp_clean %>% 
  pivot_wider(names_from = id_ind, values_from = value) %>% 
  column_to_rownames(var="symp") %>%
  # compute distances
  vegdist() %>% 
  # cluster
  hclust() 

## heat map
symp_heatmap <-
  symp_clean %>% 
  # use order proposed by clustering algorithm. Comment out to order randomly
  mutate(id_ind = factor(id_ind, 
                         levels = unique(id_ind)[individual_cluster$order])) %>%
  mutate(symp = factor(symp, 
                       levels = unique(symp)[symp_cluster$order])) %>%
  mutate(symp = fct_rev(symp)) %>% 
  # plot
  ggplot(aes(x = id_ind, y = symp, fill = value)) +
  geom_tile() +
  coord_flip()

## heat map with different colors for each
symp_heatmap_multicolor <-
  symp_clean %>% 
  # order by commonness of symptom 
  group_by(symp) %>% 
  mutate(sum_symp = sum(value)) %>% ungroup() %>% 
  mutate(symp = fct_reorder(symp, -sum_symp)) %>%
  # plot
  ggplot() +
  geom_tile(aes(x = id_ind, y = symp, fill = symp, alpha = value),height = 1, width = 0.9, size = 0) +
  guides(alpha = F, fill = F) + 
  theme_classic() + 
  labs(title = "Symptoms shown by all symptomatic individuals", 
       subtitle = "symptomatic individuals were ** % of all who tested positive",
       x = "Individuals") +
  theme(axis.text.x = element_blank()) +
  scale_fill_paletteer_d(palette = "ggthemes::Tableau_20")


## percentage showing each symptom

symp_col_plot <- 
  symp_clean %>% 
  group_by(symp) %>% 
  summarise(n = sum(value), 
            pop = length(unique(.$id_ind))) %>%  
  mutate(prop = n/pop) %>% 
  mutate(symp = fct_reorder(symp, prop)) %>% 
  ggplot() + 
  coord_flip() +
  geom_col(aes(x = symp, y = n, fill = symp)) + 
  geom_label(aes(x = symp, y= n + 3, label = percent(prop, accuracy = 0.1))) +
  scale_fill_paletteer_d(palette = "ggthemes::Tableau_20") + 
  labs(title = "Most common symptoms", 
       subtitle = "symptomatic individuals were ** % of all who tested positive",
       x = "symptoms") + 
  guides(fill = F)



```

